name: Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Deployment will go here."
      